import {
  FileText,
  Database,
  Cog,
  Info,
  Upload,
  Copy,
  BookOpen,
  User,
  LogOut,
  Home,
  LayoutDashboard,
  Settings,
  Users,
  Folder,
  Calendar,
  TrendingUp,
  BarChart2,
  Activity,
  DollarSign,
  CreditCard,
  List,
  Check,
  X,
  AlertTriangle,
  CheckCircle,
  Circle,
  ExternalLink,
  ChevronRight,
  ChevronLeft,
  MoreHorizontal,
  Trash2,
  Pencil,
  Plus,
  Minus,
  Filter,
  SearchIcon, // Renamed to avoid conflict if needed
  Loader2, // Alternative for Spinner
  Eye,
  EyeOff,
  AlertCircle,
  Bell,
  type LucideIcon,
  LayoutGrid,
  ArrowUp,
  ArrowDown,
  PlusCircle,
  Download,
  RefreshCw,
  FileStack,
  Hash,
  Maximize,
  Blocks,
  ChevronDown,
  ChevronUp,
  MessageSquare,
  Shield,
  Sparkles,
  Brain,
  Save,
  FileAudio,
  ArrowUpCircle,
  Lock,
  Truck,
  ShoppingCart,
  Leaf,
  Star,
  Package,
} from 'lucide-react';

// Exporting all icons used and potentially useful ones
export const Icons = {
  // Core UI Icons
  FileAudio: FileAudio as LucideIcon,
  Spinner: Loader2 as LucideIcon, // Using Loader2 as a more descriptive spinner
  Loader2: Loader2 as LucideIcon,
  Search: SearchIcon as LucideIcon,
  FileText: FileText as LucideIcon,
  Database: Database as LucideIcon,
  Cog: Cog as LucideIcon,
  Info: Info as LucideIcon,
  Upload: Upload as LucideIcon,
  Copy: Copy as LucideIcon,
  BookOpen: BookOpen as LucideIcon,
  User: User as LucideIcon,
  LogOut: LogOut as LucideIcon,
  ExternalLink: ExternalLink as LucideIcon,
  ChevronRight: ChevronRight as LucideIcon,
  ChevronLeft: ChevronLeft as LucideIcon,
  MoreHorizontal: MoreHorizontal as LucideIcon,
  Trash: Trash2 as LucideIcon,
  Pencil: Pencil as LucideIcon,
  Plus: Plus as LucideIcon,
  Minus: Minus as LucideIcon,
  Filter: Filter as LucideIcon,
  Check: Check as LucideIcon,
  X: X as LucideIcon,
  AlertTriangle: AlertTriangle as LucideIcon,
  CheckCircle: CheckCircle as LucideIcon,
  Circle: Circle as LucideIcon,
  Bell: Bell as LucideIcon,
  Eye: Eye as LucideIcon,
  EyeOff: EyeOff as LucideIcon,
  Alert: AlertCircle as LucideIcon,
  LayoutGrid: LayoutGrid as LucideIcon,
  List: List as LucideIcon,
  ArrowUp: ArrowUp as LucideIcon,
  ArrowDown: ArrowDown as LucideIcon,
  PlusCircle: PlusCircle as LucideIcon,
  Download: Download as LucideIcon,
  RefreshCw: RefreshCw as LucideIcon,
  FileStack: FileStack as LucideIcon,
  Hash: Hash as LucideIcon,
  Maximize: Maximize as LucideIcon,
  Blocks: Blocks as LucideIcon,
  ChevronDown: ChevronDown as LucideIcon,
  ChevronUp: ChevronUp as LucideIcon,
  MessageSquare: MessageSquare as LucideIcon,
  Shield: Shield as LucideIcon,
  Sparkles: Sparkles as LucideIcon,
  AlertCircle: AlertCircle as LucideIcon,
  Brain: Brain as LucideIcon,
  Save: Save as LucideIcon,

  // Navigation Icons (Example)
  Home: Home as LucideIcon,
  LayoutDashboard: LayoutDashboard as LucideIcon,
  Settings: Settings as LucideIcon,
  Users: Users as LucideIcon,
  Folder: Folder as LucideIcon,
  Calendar: Calendar as LucideIcon,

  // Chart/Analytics Icons (Example)
  TrendingUp: TrendingUp as LucideIcon,
  BarChart2: BarChart2 as LucideIcon,
  Activity: Activity as LucideIcon,
  DollarSign: DollarSign as LucideIcon,
  CreditCard: CreditCard as LucideIcon,
  ArrowUpCircle: ArrowUpCircle as LucideIcon,
  Lock: Lock as LucideIcon,
  Truck: Truck as LucideIcon,
  ShoppingCart: ShoppingCart as LucideIcon,
  Leaf: Leaf as LucideIcon,
  Star: Star as LucideIcon,
  Package: Package as LucideIcon,
};

// You can also export individual icons if needed elsewhere
// export { Search, FileText, Database, Cog, Info, Upload, BookOpen, Spinner };
